services:
  accounts:
    image: "786306/account:s2"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - accountms
networks:
  accountms:
    driver: "bridge"
